post http://localhost:8080/api/auth/signIn
Content-Type:  application/json

{
    "email" : "sridhar@test.com",
    "password" : "1234"
}

###
post http://localhost:8080/api/auth/signUp
Content-Type:  application/json

{
    "email" : "RadhaKrish@test.com",
    "password" : "1234"
}

###
http://localhost:8080/api/service/profileDetails
Authorization: zI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDMwMDVjN2FhZDJjMDZhM2ZlNWIwYzYiLCJlbWFpbCI6IlJhZGhhS3Jpc2hAdGVzdC5jb20iLCJpYXQiOjE2ODA4Njg4MDcsImV4cCI6MTY4MDg3NjAwN30.LZZLmC7FXZ8CJOReU4Fsd5lACOoc9EaZE27NjWLBufA